### ISSUE TITLE
DB Migrations

### ISSUE THREAD

**Issue by pizzapanther** [Miserlou/zappa-django-utils#11]
I'm using this package for PyTexas 2017's DB (https://www.pytexas.org/2017/) on Heroku since the data is light and doesn't change very much. Anyways I recently tried to do some migrations on the DB. I still had my web container running and started up a separate container to run the migrations. Everything ran fine but the web container never got the updated DB with the new columns. I also tried going into maintenance mode so when I ran the migration nothing would interfere. It still wouldn't stick. Finally, I downloaded the DB from S3 and ran the migrations on my local machine and re-uploaded the database. I also turned off versioning for the S3 bucket.

So my question is migration something special that I need to work around? Or is versioning a problem?

Are multiple containers writing to the DB a problem? I'm assuming not since Amazon Lambda scales infinitely. I'm guessing 2 Heroku containers accessing a DB at once shouldn't be a problem?

**Comment by FlipperPA** [comment]
Good question, I know SQLite is going to have issues if there are multiple concurrent writes. Quick question for you, however: are you running Python 2 or Python 3? If you got this working with Python 3, can you share how? (Sorry for the off-topic question)

**Comment by pizzapanther** [comment]
It's Python 3. I didn't do anything it just works 😀. I'm running Python 3.6.2 on heroku. https://github.com/pytexas/PyTexasBackend

**Comment by FlipperPA** [comment]
Oh, since you were in `zappa-django-utils`, I assumed you were putting this on AWS Lambda! Thanks.

**Comment by pizzapanther** [comment]
If I name my app zappa on Heroku then were all good right ;-)

The S3 DB sync is definitely applicable to many more platforms. Anywhere you need a lightweight DB on a PAAS, it's great.  Like an App Engine version for Google Cloud Storage would be awesome too. For right now, S3 suites my needs since Heroku is situated on AWS.

**Comment by pizzapanther** [comment]
Just confirmed on another project, you definitely can't migrate while anything else is running. Once I shut all my web workers down, then I could migrate and spin everyone back up. For right now this is a limitation I think should be documented. I also tried writing with multiple clients. That didn't work either.

I'll write up a doc PR is that sounds good.?

**Comment by Miserlou** [comment]
Doc PR sounds good!
