### ISSUE TITLE
Data loss in SQLite occurring occasionally: DB reverts to prior state

### ISSUE THREAD

**Issue by FlipperPA** [Miserlou/zappa-django-utils#16]
I am running `s3sqlite` on Amazon S3 with Zappa on AWS Lambda. I'm using Django 2.0 and Wagtail 2.0. It is all bleeding edge stuff - Wagtail 2.0 is straight off master - so this issue will be for collecting data and brainstorming a solution.

I have everything running at https://PyPhilly.org/ Occasionally, when I create a new page in Wagtail, it'll appear for a minute, but disappear a minute later, like the DB has reverted to a previous state. This may be because the database is in Lambda memory, but isn't being `PUT` back to S3 in the `close()` method here: https://github.com/Miserlou/zappa-django-utils/blob/master/zappa_django_utils/db/backends/s3sqlite/base.py#L58

Is anyone else experiencing issues like this? Does anyone know if there are times when Django's DB Engine won't call the `close()` method, which might be causing the DB to disappear from memory, rather than being written back to S3?

I started work on a P.R. to write after each `execute()` method, but that's going to be problematic for pages with multiple inserts, especially as the database size grows. Getting and putting the DB file back and forth as it grows seems like begging for trouble.

I've just had a P.R. merged which should make seeing problems in `zappa tail` a bit easier here: https://github.com/Miserlou/zappa-django-utils/pull/15/files#diff-8dac6662b0890c87282111cf1c72ec12L78 (see line 78 of the diff). I'll update this issue with more information as I find it.

Does anyone know what kind of performance implications there would be as the database grows in size with Amazon's infrastructure set up between S3 and Lambda? What if it grows to be 50 MB? 500 MB? The DB I'm working with is < 1MB, and I haven't tested scaling (yet).

Any thoughts, feedback, or data points would be appreciated!

**Comment by pratermade** [comment]
This issue is killing my project idea! I might have a theory but not a solution. From the S3 Website:
[Introduction to Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html) 

> Amazon S3 provides read-after-write consistency for PUTS of new objects in your S3 bucket in all regions with one caveat. The caveat is that if you make a HEAD or GET request to the key name (to find if the object exists) before creating the object, Amazon S3 provides eventual consistency for read-after-write.
> 
> Amazon S3 offers eventual consistency for overwrite PUTS and DELETES in all regions.
> 
> Updates to a single key are atomic. For example, if you PUT to an existing key, a subsequent read might return the old data or the updated data, but it will never write corrupted or partial data.

Is it possible that when you write the db to s3, then do something else it grabs an older version of the db. Then when you write it again, you overwrite your changes with the older data?

I don't have any data to support the theory at this point, but it's the best idea I've got.  Perhaps if you delete the db file, then upload the new version, it would read-after-write?

**Comment by mwalker** [comment]
I had some weirdness like this a while ago which I put down to multiple lambdas operating at once. It hasn't happened for a while, but I have been running the code in #17 and #18 during that time.

We have been happily running with a db approximately 70MB in size, but writing to the database is in a job that only happens overnight.

**Comment by FlipperPA** [comment]
Knock on wood, this hasn't happened to me in a while either. I'm wondering if it was an upstream Lambda conflict that AWS fixed. I'm still noodling on a "locking" mechanism of some sort, but not sure there is such an animal with what we're trying to do here, and introducing the complexity of timeout tracking might be more trouble than its worth.

**Comment by edmolten** [comment]
It still happens. I'm working with Django 1.11.7. After I make a change through the admin, the changes can be seen for a while, but after some refreshes they disappear.

**Comment by FlipperPA** [comment]
I think @pratermade's finding is the most likely culprit. Unfortunately, I'm not enough of an AWS expert to know how to work around it (or if it is even possible to work around).

**Comment by mwalker** [comment]
We use terraform for some other projects and store the state in S3, it uses DynamoDB to do locking of the state files. You could probably do something similar, push the hash of the latest version into DynamoDB and retry until you see that hash, dunno how well that will work though, what do you do if it doesn't/takes some time to appear? Or as @pratermade says rename the db and upload it to the bucket with a PUT each time and store the latest name in DynamoDB.

**Comment by SCDealy** [comment]
I have been investigating converting my lambda app to use SQLite, and based on my reading and the above comments, I suspect that S3 object locking does not provide the file locking capabilities required by SQLite (I have not been able to find anything on-line so far about S3 and SQLite compatibility). Amazon EFS (as of two years ago) does have this capability and specifically lists support for SQLite:

https://aws.amazon.com/about-aws/whats-new/2017/03/amazon-elastic-file-system-amazon-efs-now-supports-nfsv4-lock-upgrading-and-downgrading/

however, it appears you cannot use EFS from lambda, though many people have requested the capability:

https://forums.aws.amazon.com/thread.jspa?threadID=179785

It's never simple :-(

FWIW
