### ISSUE TITLE
create_pg_db.py: can't connect to a database which doesn't exist

### ISSUE THREAD

**Issue by royemmerich** [Miserlou/zappa-django-utils#2]
In this line you're attempting to connect to a database which doesn't yet exist.

https://github.com/Miserlou/zappa-django-utils/blob/61bb3d5d366d4ae39fa6c4ac84253b5a3ba9be38/zappa_django_utils/management/commands/create_pg_db.py#L17

Instead you should rather connect to the `postgres` database.

**Comment by millarm** [comment]
This is right - to create the initial DB this needs to be:

con = connect(dbname='postgres', user=user, host=host, password=password)

**Comment by edgarroman** [comment]
Submitted Pull Request #12

**Comment by edgarroman** [comment]
Submitted Pull Request #12

**Comment by edgarroman** [comment]
Submitted Pull Request #12
