### ISSUE TITLE
Dropping PG DB

### ISSUE THREAD

**Issue by AlmogCohen** [Miserlou/zappa-django-utils#26]
Generally dangerous but super helpful when prototyping a new service. 

If I'll create a PR to add this helper function, would it be merged? :)

**Comment by Miserlou** [comment]
Doooooooo it

**Comment by AlmogCohen** [comment]
Was just testing this one out and got zappa error:
```
psycopg2.OperationalError: database "demodb" is being accessed by other users
DETAIL:  There are 2 other sessions using the database.
```
Site is not actively used (demo site) so I assume something else is going on in the background. Maybe it is not so useful :)

**Comment by AlmogCohen** [comment]
lol, it could be that this `manage.py` command itself is the connection that prevents dropping
