### ISSUE TITLE
Error: Please define stage 'create_pg_db' in your Zappa settings.

### ISSUE THREAD

**Issue by samirtendulkar** [Miserlou/zappa-django-utils#29]
**Intro:** I am deploying a django app to AWS lambda severlessly using zappa. My RDS instance has a postgres database. I am watching [rich jones djangocon video](https://www.youtube.com/watch?v=ixRZfVBn_A8&t=911s) on how to deploy django app severlessly using zappa. So far I have managed to reach the part where I need to add a database to my project. I have already done `pip install zappa-django-utils` and added it to my `INSTALLED_APPS`. Now when I try to run

`zappa manage create_pg_db production` I get the error:

`Error: Please define stage 'create_pg_db' in your Zappa settings.`

I even tried `zappa manage create_pg_db` I am still getting the same error

Below is how my zappa_settings.json file looks:

```
{
    "production": {
        "aws_region": "us-east-1",
        "django_settings": "Cool.settings",
        "profile_name": "default",
        "project_name": "cool",
        "runtime": "python3.6",
        "s3_bucket": "cool-7dsfsdf5",
        "project_directory": "/tmp/code",
        "slim_handler": true,
        "vpc config": {
            "SubnetIds": [
                "subnet-3132ss13b",
                "subnet-321321319",
                "subnet-2c2313223",
                "subnet-5ljlkjljd",
                "subnet-132121357",
                "subnet-f925f9c7"
            ],
            "SecurityGroupIds": [
                "sg-a9asdasd"
            ]
        }
    },
    "production_ap_northeast_1": {
        "aws_region": "ap-northeast-1",
        "extends": "production"
    },
    "production_ap_northeast_2": {
        "aws_region": "ap-northeast-2",
        "extends": "production"
    },
    ... All regions..
}
```

How do I take it from here

**Comment by sathouel** [comment]
try `zappa manage production create_pg_db` in this order.

**Comment by samirtendulkar** [comment]
Thanks I connected to RDS with pgadmin updated my database and ran @sathouel 's command and it worked
