### ISSUE TITLE
[Feature Request] Additional options upon first DB creation

### ISSUE THREAD

**Issue by royemmerich** [Miserlou/zappa-django-utils#3]
I use the [**HStoreField**](https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#hstorefield) to store JSON strings in the database. In order to do so you have to connect to your newly created Django database and run the query:

`CREATE EXTENSION IF NOT EXISTS hstore;`

It would be great to offer a command line option for this (e.g. `--hstore`)

**Comment by Miserlou** [comment]
(Just saw this one, sorry!)

Yes, this would be a good feature! PR welcome!
