### ISSUE TITLE
s3sqlite: Python 3 Support

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/zappa-django-utils#9]
Related: https://github.com/Miserlou/lambda-packages/issues/66

**Comment by Miserlou** [comment]
This should work with the latest Zappa, at least there are no blockers. Haven't tested yet.

**Comment by edgarroman** [comment]
Verified working with:
Python 3.6.1
Packages:
zappa==0.45.1
zappa-django-utils==0.3.0
lambda-packages==0.19.0

**Comment by Miserlou** [comment]
Woho!

**Comment by Miserlou** [comment]
Woho!
